ClauMaj/blueTeamProject

index.html
=> added lorem

images/images.css
=> Created Images Folder

js/claude.js, readme.md
=> added readme.md

js/weather.js
=> added js file for weather

js/weather.js
=> end of day 2

js/claude.js
=> map and user location

js/claude.js
=> added map to index

css/global.css, css/navbar.css, index.html
=> Updated index

css/map.css, index.html
=> Fixed Errors

css/global.css, html/aboutus.html, index.html, js/blueTeam.js
New Index Update w/ Reactivity
=> New Index Update w/ Reactivity

index.html, js/claude.js
=> added webcam api

js/weather.js
console log of city cords weather description and weather id
=> console log of city cords weather description and weather id

index.html, js/claude.js
=> added current location api

js/weather.js
=> added filter for id = snow

js/claude.js
=> added user location

index.html
=> Updated ID for Search City

js/claude.js
=> added user input marker

js/weather.js
=> added ski resort api

css/global.css, css/navbar.css, html/aboutus.html, html/directions.html, index.html, js/blueTeam.js
Newest versions of HTML and CSS files
=> Newest versions of HTML and CSS files

html/aboutus.html, readme.md
Updated About Us Page and ReadMe
=> Updated About Us Page and ReadMe
